GET http://localhost:3100/products HTTP/1.1

###

GET http://localhost:3100/products/3 HTTP/1.1

###

POST http://localhost:3100/products HTTP/1.1
content-type: application/json

{
    "product_name": "sample",
    "price": 10,
    "quantity": 20
}

###

DELETE http://localhost:3100/products/1 HTTP/1.1
