### GET ALL

GET http://localhost:3100/products HTTP/1.1


### GET BY ID

GET http://localhost:3100/products/618e1e3dc22828385726baf2 HTTP/1.1


### SAVE

POST http://localhost:3100/products HTTP/1.1
content-type: application/json

{
    "product_name": "Product 6",
    "quantity": 10,
    "price": 5.50,
    "sale_price": 7,
    "category": "Pencil",
    "last_update_date": "11/12/2021"
}


### UPDATE

POST http://localhost:3100/products HTTP/1.1
content-type: application/json

{
    "_id": "618e1e3dc22828385726baf2",
    "product_name": "Product 1",
    "quantity": 10,
    "price": 5.50,
    "sale_price": 7,
    "category": "Pencil",
    "last_update_date": "11/12/2021"
}

### DELETE

DELETE http://localhost:3100/products/6193592bcd143cc76f0c2242 HTTP/1.1
